### ISSUE TITLE
[RFC] 提供 CSS 预处理器编译能力

### ISSUE THREAD

**Issue by wjq990112** [umijs/father#600]
## 背景

#514

## 配置项

在公共配置的中新增一项映射：

### preprocessor

- 类型：`boolean` | `less` | `sass` | `stylus`
- 默认值：`false`

指定需要使用的 CSS 预处理器，当值为 `true` 时，默认会根据文件后缀名自动选择 CSS 预处理器，你也可以手动指定为 `less` | `sass` | `stylus`，只在 Bundless 模式下生效。

```ts
// .fatherrc.ts
import { defineConfig } from 'father';

export default defineConfig({
  preprocessor: true,
  // or
  preprocessor: 'sass',
});
```

同时，也支持在 esm/cjs 的子配置项中覆盖。

```ts
// .fatherrc.ts
import { defineConfig } from 'father';

export default defineConfig({
  esm: {
    preprocessor: true,
    // or
    preprocessor: 'sass',
  },
});
```

## 产物

Bundless 的产物目前不会对引入 CSS 预处理器的 `import` 语句做转换，因此还需要额外的 JS 编译流程将 `import` 语句转换成 CSS：

```diff
- import './App.less';
+ import './App.css';
```

同时 CSS 预处理器的代码也应该被编译成 CSS：

源码：

```less
@class-prefix-button: ~'adm-button';

.@{class-prefix-button} {
  display: inline-block;
  &:focus {
    outline: none;
  }
}
```

产物：

```css
.adm-button {
  display: inline-block;
}
.adm-button:focus {
  outline: none;
}
```

## 如何实现

初步了解发现可以通过在 `builder/bundless/loaders` 中实现 CSS 预处理器相关的 transformer 即可。

由于需要额外的 JS 编译流程将 `import` 语句转换成 CSS，因此可能需要修改 `js-loader` 中的部分代码，在配置项开启时使用 `babel` | `esbuild` | `swc` 插件将 `import` 语句进行转换。
